version: '2'
services:
  ros_indigo:
    build: ./ROS_INDIGO
    image: ros_indigo:v1
 
  cafer:
    build: ./CAFER
    image: cafer:v1
    depends_on: 
      - ros_indigo

  dev_tools:
    build: ./DEV_TOOLS
    image: dev_tools:v1
    depends_on:
      - ros_indigo

  ide_data:
    build: ./IDE_DATA
    image: ide_data:v1
    volumes:
      - /home/${USER}/DockerData/catkin_ws/src:/home/docker_user/catkin_ws/src
      - /home/docker_user/catkin_ws
    command: chown -R 1000:1000 /home/docker_user/catkin_ws

  ide:
    build: ./IDE
    image: ide:v1
    depends_on:
      - dev_tools
      - ide_data
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:z
    volumes_from:
      - cafer
      - ide_data
    environment:
      - DISPLAY

  terminator:
    build: ./TERMINATOR
    image: terminator:v1
    devices:
      - /dev/bus/usb/:/dev/bus/usb/
    depends_on:
      - dev_tools
      - ide_data
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:z
    volumes_from:
      - cafer
      - ide_data
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1

  
