version: '2'
services:
  ros_indigo:
    build: ./ROS_indigo
    image: ros_indigo:v1
    volumes:
      - /opt/ros/indigo
  
  cafer:
    build: ./CAFER
    image: cafer:v1
    depends_on: 
      - ros_indigo
    volumes: 
      - /usr/local

  ide_data:
    build: ./IDE_data
    image: ide_data:v1
    volumes:
      - /home/${USER}/DockerData/catkin_ws/src:/home/docker_user/catkin_ws/src
      - /home/docker_user/catkin_ws
    command: chown -R 1000:1000 /home/docker_user/catkin_ws

  ide:
    build: ./IDE
    image: ide:v1
    depends_on:
      - cafer
      - ide_data
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:z
    volumes_from:
      - ros_indigo
      - cafer
      - ide_data
    environment:
      - DISPLAY
