version: '2'
services:
  ros_indigo:
    build: 
      context: ./ROS_INDIGO
      args:
        build_env_gid: ${env_GID}
        build_env_uid: ${env_UID}
    image: ros_indigo:v1
   

  dev_tools:
    build: ./DEV_TOOLS
    image: dev_tools:v1
    depends_on:
      - ros_indigo

  cafer:
    build: ./CAFER
    image: cafer:v1
    depends_on: 
      - dev_tools
    volumes:
      - /home/docker_user/ros_packages/cafer_core

  ide_data:
    build: ./IDE_DATA
    image: ide_data:v1
    volumes:
      - /home/${USER}/DockerData/catkin_ws/src:/home/docker_user/catkin_ws/src
      - /home/docker_user/catkin_ws
    command: chown -R ${env_UID}:${env_GID} /home/docker_user/catkin_ws

  terminator:
    build: ./TERMINATOR
    image: terminator:v1
    devices:
      - /dev/bus/usb/:/dev/bus/usb/
    depends_on:
      - cafer
      
  ide:
    build: ./IDE
    image: ide:v1
    depends_on:
      - terminator
      - ide_data
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:z
    volumes_from:
      - cafer
      - ide_data
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    entrypoint: 
      - /usr/bin/terminator
    security_opt:
      - seccomp:unconfined
   

  
