version: '2'
services:
  ros_indigo:
    build: ./ROS_INDIGO
    image: ros_indigo:v1

  dev_tools:
    build: ./DEV_TOOLS
    image: dev_tools:v1
    depends_on:
      - ros_indigo

  cafer:
    build: ./CAFER
    image: cafer:v1
    depends_on: 
      - dev_tools
    volumes:
      - /home/docker_user/ros_packages/cafer_core

  ide_data:
    build: ./IDE_DATA
    image: ide_data:v1
    volumes:
      - ${USERPROFILE}/DockerData/catkin_ws/src:/home/docker_user/catkin_ws/src
      - /home/docker_user/catkin_ws
    command: chown -R 1000:1000 /home/docker_user/catkin_ws

  ide:
    build: ./IDE
    image: ide:v1
    depends_on:
      - dev_tools
      - ide_data
    volumes_from:
      - cafer
      - ide_data
    environment:
      - DISPLAY=10.0.75.1:0.0
      - QT_X11_NO_MITSHM=1

  terminator:
    build: ./TERMINATOR
    image: terminator:v1
    depends_on:
      - dev_tools
      - ide_data
    volumes_from:
      - cafer
      - ide_data
    environment:
      - DISPLAY=10.0.75.1:0.0
      - QT_X11_NO_MITSHM=1

  
